### ISSUE TITLE
Better CI error logs

### ISSUE THREAD

**Issue by eskimor** [polkadot-fellows/runtimes#224]
CI Kusama migration is failing on CI and [all the output](https://github.com/polkadot-fellows/runtimes/actions/runs/8176007688/job/22354705380?pr=206) I see is:

```
Error: <blank void>
```

Can we get more logging. This one is particularly annoying, because it passes just fine for me locally. Works on my machine TM

**Comment by bkchr** [comment]
```
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "NominationPools" VersionedMigration migrating storage version from 7 to 8.
[2024-03-06T17:54:07Z INFO  runtime::staking] [22178236] 💸 v14 applied successfully.
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "Configuration" VersionedMigration migrating storage version from 9 to 10.
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "Configuration" VersionedMigration migrating storage version from 10 to 11.
[2024-03-06T17:54:07Z INFO  runtime::configuration] HostConfiguration MigrateToV11 started
[2024-03-06T17:54:07Z INFO  runtime::configuration] HostConfiguration MigrateToV11 executed successfully
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "Grandpa" VersionedMigration migrating storage version from 4 to 5.
[2024-03-06T17:54:07Z INFO  runtime::identity::migration::v1] pre-upgrade state contains '4241' identities.
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "Identity" VersionedMigration migrating storage version from 0 to 1.
[2024-03-06T17:54:07Z INFO  runtime::identity::migration::v1] running storage migration from version 0 to version 1.
[2024-03-06T17:54:07Z INFO  pallet_identity::migration::v1] all 4241 identities migrated
[2024-03-06T17:54:07Z INFO  pallet_identity::migration::v1] post-upgrade expects '4241' identities to have been migrated.
[2024-03-06T17:54:07Z INFO  runtime::identity::migration::v1] migrated all identities.
[2024-03-06T17:54:07Z INFO  frame_support::migrations] 🚚 Pallet "ParaScheduler" VersionedMigration migrating storage version from 1 to 2.
[2024-03-06T17:54:07Z INFO  runtime::parachains::scheduler] Migrating para scheduler storage to v2
[2024-03-06T17:54:07Z INFO  polkadot_runtime_parachains::coretime::migration::v_coretime] Migrating existing parachains to coretime.
[2024-03-06T17:54:07Z INFO  runtime::session_keys] Collecting pre-upgrade session keys state
[2024-03-06T17:54:07Z INFO  runtime::session_keys] Session keys migrated successfully
[2024-03-06T17:54:07Z INFO  frame_support::migrations] Found ImOnline keys pre-removal 👀
[2024-03-06T17:54:08Z INFO  frame_support::migrations] Removed 500 ImOnline keys 🧹
[2024-03-06T17:54:08Z INFO  frame_support::migrations] No ImOnline keys found post-removal 🎉
[2024-03-06T17:54:19Z ERROR runtime::executive] `try_decode_entire_state` failed with 1 errors
[2024-03-06T17:54:19Z ERROR runtime::executive] - 0. error: `System::Events` key `0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7` is undecodable
[2024-03-06T17:54:19Z ERROR runtime] panicked at /home/runner/work/runtimes/runtimes/relay/kusama/src/lib.rs:2471:65:
    called `Result::unwrap()` on an `Err` value: Other("`try_decode_entire_state` failed")
thread 'main' panicked at cli/main.rs:320:10:
called `Result::unwrap()` on an `Err` value: Input("failed to execute TryRuntime_on_runtime_upgrade: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x6c2f - <unknown>!rust_begin_unwind\n    1: 0x37ac - <unknown>!core::panicking::panic_fmt::h70184a08c78ac6ca\n    2: 0x3d43 - <unknown>!core::result::unwrap_failed::h071aa3f1749a13dc\n    3: 0x75c406 - <unknown>!TryRuntime_on_runtime_upgrade")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I see this? Not sure what else you need?

**Comment by bkchr** [comment]
Cc @eskimor
